### ISSUE TITLE
Hi, it's possible to use any UEs and one eNode on srsRAN 22.04.1 with zeromq?

### ISSUE THREAD

**Issue by artho2022** [srsran/srsRAN_4G#1012]
## Issue Description ##
[Describe the issue in detail]

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions

## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by brendan-mcauliffe** [comment]
To provide any useful information you will need to describe in further detail exactly what you are trying to do. I would also suggest sending questions like this to the [mailing list](https://lists.srsran.com/mailman/listinfo/srsran-users), instead of opening GitHub issues - as this is not an issue with the code base.

**Comment by andrepuschmann** [comment]
Perhaps the Gnu Radio handover examples could help you to modify them to connect multiple UEs.
